### ISSUE TITLE
FBTrace and process isolation

### ISSUE THREAD

**Issue by cadorn** [firebug/tracing-console#8]
How does FBTrace render expandable objects across processes or does it?

**Comment by cadorn** [comment]
$feature https://github.com/firephp/firephp-for-firebug.next/issues/1

**Comment by janodvarko** [comment]
I implemented simple support in this revision
https://github.com/firebug/tracing-console/commit/c5520e210996f5d743bf6c3ae21e038d99e60ad4
(search for sendSyncMessage in the code)

Related to issue #241

If a child process wants to get the tracer it does it as follows:

````
let scope = {};
Cu["import"]("resource://fbtrace/firebug-trace-service.js", scope);
let FBTrace = scope.traceConsoleService.getTracer("extensions.firebug",
  sendSyncMessage);
````

It provides `sendSyncMessage` function (coming from the child message manager) to the tracer object. The tracing console is consequently using this function to send the log into the parent process to display it in the UI. If an object is passed into the log, it's serialised into JSON (if possible)

Honza
